import Module from '@app/module/Module';
import Model from './Model';

/**
 * Model that defines the displacement of a line segment.
 *
 * This model returns an output value from a noise module given the
 * one-dimensional coordinate of an input value located on a line
 * segment, which can be used as displacements.
 *
 * This class is useful for creating:
 *  - roads and rivers
 *  - disaffected college students
 *
 * To generate an output value, pass an input value between 0.0 and 1.0
 * to the getValue() method.  0.0 represents the start position of the
 * line segment and 1.0 represents the end position of the line segment.
 */
class Line extends Model {
  /**
   * A flag that specifies whether the value is to be attenuated
   * (moved toward 0.0) as the ends of the line segment are approached.
   */
  public attenuate: boolean;

  // @TODO convert to a matrix
  private x0: number;
  private x1: number;
  private y0: number;
  private y1: number;
  private z0: number;
  private z1: number;

  /**
   * @param sourceModule The noise module that is used to generate the output values.
   */
  constructor(sourceModule: Module) {
    super(sourceModule);

    this.attenuate = true;
    this.x0 = 0.0;
    this.x1 = 1.0;
    this.y0 = 0.0;
    this.y1 = 1.0;
    this.z0 = 0.0;
    this.z1 = 1.0;
  }

  /**
   * Returns the output value from the noise module given the
   * one-dimensional coordinate of the specified input value located
   * on the line segment.
   *
   * The output value is generated by the noise module passed to the
   * SetModule() method.  This value may be attenuated (moved toward
   * 0.0) as p approaches either end of the line segment; this is
   * the default behavior.
   *
   * If the value is not to be attenuated, p can safely range
   * outside the 0.0 to 1.0 range; the output value will be
   * extrapolated along the line that this segment is part of.
   *
   * @param p The distance along the line segment (ranges from 0.0 to 1.0)
   *
   * @returns The output value from the noise module.
   */
  public getValue(p: number): number {
    let value = this.sourceModule.getValue(
      (this.x1 - this.x0) * p + this.x0,
      (this.y1 - this.y0) * p + this.y0,
      (this.z1 - this.z0) * p + this.z0,
    );

    return this.attenuate ? (p * (1.0 - p) * 4 * value) : value;
  }

  /**
   * Sets the position ( x, y, z ) of the end of the line
   * segment to choose values along.
   *
   * @param x x coordinate of the end position.
   * @param y y coordinate of the end position.
   * @param z z coordinate of the end position.
   */
  public setEndPoint(x: number, y: number, z: number): void {
    this.x1 = x;
    this.y1 = y;
    this.z1 = z;
  }

  /**
   * Sets the position ( @a x, @a y, @a z ) of the start of the line
   * segment to choose values along.
   *
   * @param x x coordinate of the start position.
   * @param y y coordinate of the start position.
   * @param z z coordinate of the start position.
   */
  public setStartPoint(x: number, y: number, z: number): void {
    this.x0 = x;
    this.y0 = y;
    this.z0 = z;
  }

}

export default Line;
