import Module from '@app/module/Module';

/**
 * Base class for generate modules.
 * Generator modules output a value generated by a coherent-noise
 * function or some other mathematical function.
 */
export default abstract class GeneratorModule extends Module {
}